### ISSUE TITLE
Target #75 (Hippo) stuck on 99.9% 

### ISSUE THREAD

**Issue by Connum** [cssbattle/forum#102]
I can't get target #75 (Hippo) to 100%, despite no pixels moving when hovering the preview area. There may be som sub-pixel differences, but I had other targets at 100% with some edges or elements visibly shifting at least 1px. 

In fact, the closer I get to perfection using decimal pixel values for positoning, the lower the score seems to get... Something can't be right! I'm using an up-to-date Chrome.

Can I somehow provide my solution without spoiling the target for others?

**Comment by chinchang** [comment]
Try to use the new "See differences" feature and see if you can find the mismatch https://twitter.com/css_battle/status/1446908015756541954?s=20
