### ISSUE TITLE
Wrong status label after switching battles

### ISSUE THREAD

**Issue by Connum** [cssbattle/forum#106]
When being on the overview page of a finished battle and then using the dropdown to select Battle #15, which currently has the status "Upcoming", the status label doesn't change from the red "Finished" label to the yellow "Upcoming" label.

**Steps to reproduce:**
1. visit https://cssbattle.dev/battle/14
2. use the dropdown next to the logo to change to Battle # 15

**Result:**
![image](https://user-images.githubusercontent.com/13076806/134136754-ac810e81-98ef-4436-b919-62e251eca2ab.png)

**Expected Result:**
(this works when navifating to Battle # 15 from the home page, opening the URL https://cssbattle.dev/battle/15 directly, or refreshing the page after executing the stepsabove)
![image](https://user-images.githubusercontent.com/13076806/134136935-c0945ff1-8360-4372-bb79-4d57fb4d3384.png)

**Comment by Connum** [comment]
By the way, it's the same with the label "In Progress". However, it works the other way round, when switching from target # 15 to a target with the label "Finished".

**Comment by chinchang** [comment]
fixed now :)
