### ISSUE TITLE
website is not getting open

### ISSUE THREAD

**Issue by himanshubhatt1** [cssbattle/forum#116]
### Discussed in https://github.com/cssbattle/forum/discussions/115

<div type='discussions-op-text'>

<sup>Originally posted by **himanshubhatt1** October  5, 2021</sup>
![error](https://user-images.githubusercontent.com/80446990/136020012-1e3d6900-fde3-4217-bb33-7f857108deb3.png)
In last few days i am not able to open CSS BATTLE , I have tried all my side,but no solution ...please help.</div>

**Comment by chinchang** [comment]
Hi! Seems like your network issue. Can you try opening on your mobile
internet?
