### ISSUE TITLE
Wrong size of solution preview

### ISSUE THREAD

**Issue by SkyHolder** [cssbattle/forum#131]
In the solution preview, the content is stretched to the full width of the code
https://yadi.sk/i/LkcV3Nv8cCMQ_A 

beause of 
```
.dropdown-menu{
...
    min-width: max-content;
}
```
https://yadi.sk/i/uFKaBMzUws3W-Q

it can be replaced by 
`min-width: 100%`
https://yadi.sk/i/TJC-q9T9tlvKjQ

**Comment by chinchang** [comment]
fixed now. Thanks for reporting @SkyHolder 🙏🏼
