### ISSUE TITLE
Switching from battle 14 to 15 doesn't update the 'finished' status (I was shocked for a moment :)

### ISSUE THREAD

**Issue by Esger** [cssbattle/forum#134]
![Schermafbeelding 2021-10-15 om 01 44 10 kopie](https://user-images.githubusercontent.com/70047/137410364-28414242-f18e-4e61-b853-facac8db4b5d.png)

**Comment by Esger** [comment]
Probably related to #106

**Comment by chinchang** [comment]
fixed now :) sorry about that! 😅
