### ISSUE TITLE
pro suggestion

### ISSUE THREAD

**Issue by RazvanManolache** [cssbattle/forum#147]
Fine, you convinced me to get the pro. Having history of all my attempts is important to me.

Now that I have it, it's kinda... meh.

First of all, why do you have to scroll the right in analytics? Tile them. Maybe even a grid.

Second. While character difference is fine, points difference would be more useful. Yes, my hippo is  562 characters away from the top score. But that top score is also only 23 points ahead. For web maker logo I'm 80 characters behind, but that is 71 points. Which one should I improve? I'll tell you, the second one.

Lastly, a great idea would be to allow to search through your top solutions for each target for key words. If I learn something new, to see which of my solutions use a certain method, and try to change it. That would make having a pro account... pro.

Just my 2 cents.

**Comment by chinchang** [comment]
> First of all, why do you have to scroll the right in analytics? Tile them. Maybe even a grid.

We'll improve this! Thanks for pointing this...we should have noted this before 😅

> Second. While character difference is fine, points difference would be more useful. Yes, my hippo is 562 characters away from the top score. But that top score is also only 23 points ahead. For web maker logo I'm 80 characters behind, but that is 71 points. Which one should I improve? I'll tell you, the second one.

Probably, sorting option by "score" and "points" both would make more sense here. 

> Lastly, a great idea would be to allow to search through your top solutions for each target for key words. If I learn something new, to see which of my solutions use a certain method, and try to change it. That would make having a pro account... pro.

You can still do that, no?
![image](https://user-images.githubusercontent.com/379918/139588724-0a8299bb-15a7-47d4-aee7-086dcbe7429e.png)

**Comment by RazvanManolache** [comment]
I can do that for one target. I want to find which of my top solutions for each target uses gradient as an example.

**Comment by RazvanManolache** [comment]
oh, and sort by your own rank for each challenge would be good too.

**Comment by chinchang** [comment]
@RazvanManolache Update here: We did a lot of the above-mentioned improvements on the /me analytics page. We'll be working on other improvements too in the coming days.

**Comment by chinchang** [comment]
> I can do that for one target. I want to find which of my top solutions for each target uses gradient as an example.

This is now live on the /me page
![image](https://github.com/user-attachments/assets/22b564a0-45a8-4b51-91e7-a34155cf2974)


Thanks for suggesting.
