### ISSUE TITLE
Page content `Y` overflow on smaller screens

### ISSUE THREAD

**Issue by wblazej** [cssbattle/forum#186]
On the home page there is a global leaderboard which is expanded on hover. Under this leaderboard there is a button "See top 100" that redirects to page with entire leaderboard. Unfortunately, on small screens (e.g. laptop 13") content overflows on `Y` so you cannot see the button (and possibly some other stuff too).

Here's POV for quick example:
![image](https://user-images.githubusercontent.com/62674438/143312796-a1156ef2-2f94-4949-a0e3-f865d85aefb4.png)

**Comment by chinchang** [comment]
Noted! we'll fix this.,

**Comment by chinchang** [comment]
fixed
