### ISSUE TITLE
Battle #17 - can't get rank

### ISSUE THREAD

**Issue by SkyHolder** [cssbattle/forum#229]
i was started this battle after finish, but my rank still 0 after complete all tasks
https://disk.yandex.ru/i/6Vx4ehENonzyXA

**Comment by LelouchFR** [comment]
It is because the battle has been finished 2 months ago, after the timer of the battle finish, there is no more possible way to grind in the battle, but can only grind in the global rank.

**Comment by SkyHolder** [comment]
but I was able to get a rank in the old battles that started to take place after they were completed

**Comment by chinchang** [comment]
As @LelouchFR mentioned, you can't get or improve your battle rank in a battle that has ended. Only in-progress battles are open to rank updates.
