### ISSUE TITLE
/me (analytics) crashes

### ISSUE THREAD

**Issue by ludviglindblom** [cssbattle/forum#268]
### Discussed in https://github.com/cssbattle/forum/discussions/267

<div type='discussions-op-text'>

<sup>Originally posted by **ludviglindblom** June  9, 2022</sup>
When I visit the [analytics page](https://cssbattle.dev/me) it shows up for a brief moment, displaying the loading animation the the text **Chrunching your stats...** and then it crashes.

The screen just says 

> Application error: a client-side exception has occurred (see the browser console for more information).

And in the console it reads as in the attached image:

<img width="644" alt="Screenshot 2022-06-09 at 15 42 09" src="https://user-images.githubusercontent.com/445328/172862464-6c7a51be-2917-43b7-96d8-630638ba62db.png"></div>

**Comment by chinchang** [comment]
Sorry about that...locked targets were messing the logic there 😅. Fixed now!
