### ISSUE TITLE
Client-side exception when logged in.

### ISSUE THREAD

**Issue by panik-kalm-panik** [cssbattle/forum#366]
As long as I'm not signed in, the web works fine. But if I sign in, the page won't load. Checked the console log and got this: 
```
[2023-11-15T22:51:54.416Z]  @firebase/firestore: Firestore (10.0.0):
Uncaught Error in snapshot listener: FirebaseError: [code=permission-denied]: Missing or insufficient permissions.
```
Things I've tried:
- Clearing cache and cookies.
- Changing browser.
- Restarting and changing devices.
- Disabling extensions. 

Got this issue on Nov 15th 11:00pm (GMT+1)

**Comment by chinchang** [comment]
This should be fixed now. Please let me know if this is still happening on your side.
