### ISSUE TITLE
Profile navigation issue

### ISSUE THREAD

**Issue by arunvinesh81** [cssbattle/forum#376]
I encounterd the issue in profile navigation, below are the steps

1. From CSS battle home, navigate to the leaderboards and click any profile eg. Beo. Beo's profile loaded

![image](https://github.com/cssbattle/forum/assets/15837629/ea72b086-6a22-41d3-b4ca-25ad4235f280)

2. Next click on your "**Profile**" in the side navigation or under your profile picture "**View profile**" which navigate to your profile link but still shows the existing profile information

![image](https://github.com/cssbattle/forum/assets/15837629/91a58c82-4191-433d-91ea-21fffc26c8b3)

3. When we reload the page, it shows the correct profile information

**Additional Info:** Browser used Google Chrome

**Comment by chinchang** [comment]
This is fixed now
