### ISSUE TITLE
cssbattle.dev is very laggy

### ISSUE THREAD

**Issue by seulgiism** [cssbattle/forum#395]
Hello,

I am running a macbook pro mid 2015 model on the arc browser.
Everything runs fine and I have a high speed fibre connection.

However, when I go on cssbattle.dev the lag or input lag is really beyond belief. Especially when animations play during the learning course when you complete something.

Is there a way to fix this from my end?

edit; tested multiple browsers, they all lag. Other websites work normally.

**Comment by chinchang** [comment]
Hi @seulgiism 
Apologies for the inconvenience caused because of the lag.
I have just shipped 2 settings within the course that might help to boost the performance.
I request you to please try switching off "Show confetti" and switch on "Force reduced motion" in the settings, like so:
![CleanShot 2024-08-29 at 18 22 09](https://github.com/user-attachments/assets/db21c8d8-bf20-4179-af7b-6ae4dae628fc)


please let me know how it works for you.

**Comment by seulgiism** [comment]
> Hi @seulgiism Apologies for the inconvenience caused because of the lag. I have just shipped 2 settings within the course that might help to boost the performance. I request you to please try switching off "Show confetti" and switch on "Force reduced motion" in the settings, like so: ![CleanShot 2024-08-29 at 18 22 09](https://private-user-images.githubusercontent.com/379918/362695027-db21c8d8-bf20-4179-af7b-6ae4dae628fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MzY2OTEsIm5iZiI6MTcyNDkzNjM5MSwicGF0aCI6Ii8zNzk5MTgvMzYyNjk1MDI3LWRiMjFjOGQ4LWJmMjAtNDE3OS1hZjdiLTZhZTRkYWU2MjhmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQxMjU5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjJmNTBkNDU1MzI3MjViMzhlMTBmMzRjNjYwOTE4NDQ0NzkyNWRiZjI4MjEzNDdmODU5OTQzYTliYjY0YmY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PidB64_Z5iciIJuZmJ-duY4lt-se1csmB2k44464dy0)
> 
> please let me know how it works for you.

It has improved in that the website feels more comfortable to use. It feels less sluggish during the lessons too, but it is definitely still there if I do a direct comparison to a self hosted code-server that also runs in the browser.

Thank you for adding these settings in.

**Comment by chinchang** [comment]
Good to hear. I'll be diving more in coming days to see how the performance can be improved further.
Thanks for reporting.

**Comment by chinchang** [comment]
@seulgiism I just deployed a few fixes to improve performance. Let me know if things improved for you any bit?

**Comment by seulgiism** [comment]
> @seulgiism I just deployed a few fixes to improve performance. Let me know if things improved for you any bit?

The performance is a huge improvement. It's crazy good; even the lessons feel super smooth than before. It's great!

**Comment by chinchang** [comment]
@seulgiism Am so glad to hear that! Appreciate the update 🙏🏼
