### ISSUE TITLE
Side menu bouncing on hover

### ISSUE THREAD

**Issue by Evavic44** [cssbattle/forum#63]
I noticed whenever I hover on the side menu bar, it starts bouncing. I'm not sure if it's supposed to act this way or an issue that requires fixing, so check it out below. 👇🏾 
![A](https://user-images.githubusercontent.com/62628408/121751970-20c62c00-cb07-11eb-9db2-4a5725a01371.gif)

**Comment by chinchang** [comment]
fixed. thanks for reporting
