### ISSUE TITLE
Add Validation to Learn Subscription Form

### ISSUE THREAD

**Issue by shrihari689** [cssbattle/forum#70]
### Discussed in https://github.com/cssbattle/forum/discussions/66

<div type='discussions-op-text'>

<sup>Originally posted by **shrihari689** June 13, 2021</sup>
Just a small bug 🐛

🚀 Steps to Reproduce

Below form at https://cssbattle.dev/learn can be submitted with empty value and `https://formspree.io/` requests fails with that.
![image](https://user-images.githubusercontent.com/57325503/121810659-57bf4d80-cc7f-11eb-8c7f-f9a9f3c129fe.png)

🧭 Possible Solution

If a user is logged in, the input field may not be necessary as we can get the email from firebase auth 📍
If a user is not logged in, add a required validation to form 📍   </div>

**Comment by chinchang** [comment]
done! Thanks for reporting :)
