### ISSUE TITLE
Usernames can be changed once set

### ISSUE THREAD

**Issue by shrihari689** [cssbattle/forum#71]
### Discussed in https://github.com/cssbattle/forum/discussions/67

<div type='discussions-op-text'>

<sup>Originally posted by **shrihari689** June 13, 2021</sup>
🚀 Steps to reproduce 

 - Go to https://cssbattle.dev/settings
 - If you have already a username, just `Inspect Element` and remove `readonly` attribute in the input field.
 - Now when you type, it fetches the availability and its changeable.

🎯 Possible Solution

 - I guess, if the user has `username` from `api/playerProfile` (it means user already set an username), then we may hide the button and block `onChange` listener of the input field.  </div>

**Comment by C-137-9527** [comment]
hi

**Comment by C-137-9527** [comment]
console.log('hello world')

**Comment by prakash-niroula** [comment]
idk how it still works in 2022 lol :)

**Comment by chinchang** [comment]
fixed! 😄
