### ISSUE TITLE
ultra-wide column on top 100

### ISSUE THREAD

**Issue by gunnarbittersmann** [cssbattle/forum#96]
On target 53, somebody made it into the [top 100](https://cssbattle.dev/leaderboard/target/53) whose name is very long and doesn’t break. This makes the table column very wide and forces horizontal scrolling.

You might want to use `overflow: hidden` possibly paired with `text-overflow: ellipsis` in your style sheet.

Or `overflow-wrap: break-word` or `overflow-wrap: anywhere`, see [this lightning talk](https://noti.st/gunnarbittersmann/AyMvbr/til-ueber-die-donaudampfschifffahrtsgesellschaftskapitaenskajuetentuerschwelle) of mine.

**Comment by chinchang** [comment]
this is fixed.
